### ISSUE TITLE
Publish a single Docker image for the whole app

### ISSUE THREAD

**Issue by aalex** [walachewaka/The-Record-Pool#26]
Publish a single Docker image for the whole app

## Criteria
- Put both frontend and backend in a single Docker image
- Publish it
- It should be easy to deploy
- The database migration should be included.

## Technical details
See radarr or sonarr: it pulls the image from Github directly:

```
---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
      - /path/to/tvseries:/tv #optional
      - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
```
