### ISSUE TITLE
Unable to mount volume in docker-compose.yml

### ISSUE THREAD

**Issue by walachewaka** [walachewaka/The-Record-Pool#42]
Expected result:
- mount _data volume to docker container - relaying local volume to container volume

Current error:
- Error response from daemon: "error while mounting volume '/var/snap/docker/common/var-lib-docker/volumes/open-record-pool_music-data/_data': failed to mount local volume: mount /tmp/music:/var/snap/docker/common/var-lib-docker/volumes/open-record-pool_music-data/_data, flags: 0x1000: no such file or directory"

**Comment by aalex** [comment]
@walachewaka Does your `/tmp/music/` folder exist?

Can you share your `docker-compose.override.yml` file?

**Comment by walachewaka** [comment]
```
version: "3.7"
services:
  frontend:
    environment:
      # Specify the host of the backend:
      - VUE_APP_BACKEND_URL=http://localhost:5000/

  backend:
    environment:
      # Allow the frontend to access the backend:
      - ALLOW_ORIGINS=http://localhost:8088

  adminer:
    ports:
      # Expose the adminer port, to ease database administration:
      - "8087:8080"

volumes:
  music-data:
    driver_opts:
      # Change this for the path to your music files:
      o: bind
      type: none
      device: /home/walachewaka/music/
```
